### ISSUE TITLE
Замечания по 7.1

### ISSUE THREAD

**Issue by sergey-shambir** [7kia/Theory-programming#1]
- память, выделенная в startProgram через new, не освобождена через delete
- левая неиспользуемая константа currentFolder

**Comment by 7kia** [comment]
- Создан деструктор для Program, в нём освобождается память выделенная для window.
- currentFolder удалил.
- Компилятор не выдаёт предупреждений.
  Как решил проблему:
- изменил тип констант thikness на float
- CENTER_WINDOW тоже на float,не int, потому-что 6 объектам задаётся начальная позиция CENTER_WINDOW(Vector2f), при создании и изменении размеров приводится к типу unsigned int(3 раза). Если был бы int, то 6 раз пришлось бы приводить к типу float, а так только 3 раза приводим к типу unsigned int.

**Comment by sergey-shambir** [comment]
Принято
